/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista; // Se declara el paquete al que pertenece esta clase.

import DatosBiblioteca.Libros; // Se importa la clase Libros para poder crear y manipular objetos libro.
import Gestion.GestorLibros; // Se importa la clase GestorLibros que funciona como controlador del sistema.

 /**
 * @author  Weymer Orocú Amador
 * Nombre del Proyecto: Sistema de Gestión y Registro de Libros
 * Descripcion del proyecto: El sistema consiste en una aplicacion desarrollada en Java Swing 
 * bajo el patrón MVC, que permite el registro, edición, búsqueda y listado de libros en tiempo 
 * real mediante el manejo de colecciones en memoria.
 */

public class VentanaPrincipal extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());   // Logger utilizado para registrar errores del sistema.
    private GestorLibros controlador; // Objeto controlador encargado de administrar la lista de libros.
    private java.text.SimpleDateFormat formatoFecha; // Objeto utilizado para convertir fechas entre texto y Date.
    private Libros LibroEdicion; // Almacena el libro seleccionado actualmente para modificar
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() { // Constructor
        initComponents();
        controlador = new GestorLibros(); // Se crea el controlador que administrará todos los libros.
        formatoFecha = new java.text.SimpleDateFormat("dd/MM/yyyy"); // Da formato a la fecha.
        formatoFecha.setLenient(false); // Impide aceptar fechas inválidas
        setLocationRelativeTo(null); // Centra la ventana en la pantallade manrea automatica.
        jLabel2.setForeground(java.awt.Color.BLUE); // Cambia el color del mensaje de estado a azul.
        jLabel2.setText("Sistema iniciado correctamente"); // Muestra un mensaje indicando que el sistema inició correctamente.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtBiblioteca = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnInsercion = new javax.swing.JButton();
        btnListarTodo = new javax.swing.JButton();
        btnMergeSort = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInvertidas = new javax.swing.JTable();
        btnInvertidas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestion de Bibliotecas");

        jLabel1.setText("Título del Libro");

        jLabel3.setText("Autor");

        jLabel4.setText("Fecha");

        jLabel5.setText("Biblioteca");

        txtTitulo.addActionListener(this::txtTituloActionPerformed);

        btnRegistrar.setText("Registrar Libro");
        btnRegistrar.setActionCommand("");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título del Libro", "Autor", "Fecha de Publicación", "Biblioteca"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btnRegistrar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Libro", jPanel1);

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnInsercion.setText("Orden Ascendente");
        btnInsercion.addActionListener(this::btnInsercionActionPerformed);

        btnListarTodo.setText("Lista");
        btnListarTodo.addActionListener(this::btnListarTodoActionPerformed);

        btnMergeSort.setText("Orden Descendente");
        btnMergeSort.addActionListener(this::btnMergeSortActionPerformed);

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título ", "Autor", "Fecha", "Biblioteca"
            }
        ));
        tablaLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLibrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaLibros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnListarTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsercion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMergeSort)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnListarTodo)
                    .addComponent(btnInsercion)
                    .addComponent(btnMergeSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Busqueda y Edición", jPanel2);

        tablaInvertidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Biblioteca Original", "Nombre Invertido"
            }
        ));
        jScrollPane1.setViewportView(tablaInvertidas);

        btnInvertidas.setText("Invertir Nombres");
        btnInvertidas.addActionListener(this::btnInvertidasActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnInvertidas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(btnInvertidas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Bibliotecas Invertidas", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("UNED");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        // Extrae el texto de las cajas y elimina espacios en blanco sobrantes a los lados (.trim)
        String titulo = txtTitulo.getText().trim(); 
        String autor = txtAutor.getText().trim();
        String fecha = txtFecha.getText().trim();
        String biblioteca = txtBiblioteca.getText().trim();
        // Validación de campos vacíos para evitar errores de datos en las listas
        if (titulo.isEmpty() || autor.isEmpty() || fecha.isEmpty() || biblioteca.isEmpty()) {
        jLabel2.setForeground(java.awt.Color.RED);
        jLabel2.setText("Error: Todos los campos son obligatorios.");
        return;
        }
        try {
        java.util.Date fechaParseada = formatoFecha.parse(fecha); // Transforma la cadena de texto de la fecha
        // Determina si el sistema guarda un registro nuevo o actualiza uno existente
        if (LibroEdicion != null) {
            // Modifica los atributos del objeto localizado en la memoria
            LibroEdicion.setTitulo(titulo);
            LibroEdicion.setAutor(autor);
            LibroEdicion.setFechaPublicacion(fechaParseada);
            LibroEdicion.setBiblioteca(biblioteca);
            jLabel2.setForeground(new java.awt.Color(0, 128, 0));
            jLabel2.setText("Libro editado con éxito.");
            // Limpiamos la variable para salir del modo edición
            LibroEdicion = null; 
            btnRegistrar.setText("Registrar Libro");
        } 
        else { // Solo entra aquí si no habíamos seleccionado nada de la tabla
            int nuevoId = controlador.getListaLibros().size() + 1; // Se genera un nuevo ID tomando la cantidad de libros existentes
            Libros nuevoLibro = new Libros(nuevoId, titulo, autor, fechaParseada, biblioteca); // Se crea un nuevo objeto de tipo Libros con los datos
            controlador.agregarLibro(nuevoLibro);  // Se envía el nuevo libro al controlador para agregarlo a la Lista.            
            jLabel2.setForeground(new java.awt.Color(0, 128, 0));
            jLabel2.setText("Libro registrado con éxito.");
        }
        // Limpia los campos del formulario
        txtTitulo.setText(""); txtAutor.setText(""); txtFecha.setText(""); txtBiblioteca.setText("");
        // Solo actualizamos la tabla de la pestaña 1
        actualizarTablaVisual(controlador.obtenerTodosLosLibros(), jTable1);
        
        } catch (java.text.ParseException e) { // Captura un error se si ingresa una fecha invalida.
        jLabel2.setForeground(java.awt.Color.RED);
        jLabel2.setText("Error: Formato de fecha inválido.");
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void actualizarTablaVisual(java.util.ArrayList<Libros> lista, javax.swing.JTable tablaDestino) {
        // Obtiene el modelo de datos asociado a la tabla destino y permite modificar las filas
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaDestino.getModel();
        modelo.setRowCount(0); // Esto borra las filas anteriores para no duplicar datos
        for (Libros l : lista) { // Recorre cada libro almacenado en la lista recibida.
            modelo.addRow(new Object[]{ // Agrega una nueva fila a la tabla con la información
            l.getId(),  // Agrega el ID único del libro.
            l.getTitulo(), // Agrega el título del libro.
            l.getAutor(), // Agrega el nombre del autor.
            formatoFecha.format(l.getFechaPublicacion()), // Convierte la fecha de publicación al formato ya establecido.
            l.getBiblioteca()
        });
    }
}
    private void btnMergeSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeSortActionPerformed
        // TODO add your handling code here:
        java.util.ArrayList<Libros> lista = controlador.obtenerTodosLosLibros();  // Obtiene la lista completa de libros almacenados en el controlador.
        controlador.ordenarPorMergeSortManual(lista); // Ordena la lista de forma descendente 
        actualizarTablaVisual(lista, tablaLibros); // Actualiza la interfaz de la tabla y los muestra
        jLabel2.setForeground(new java.awt.Color(0, 128,0));
        jLabel2.setText(" Lista ordenada descendentemente");
    }//GEN-LAST:event_btnMergeSortActionPerformed

    private void btnListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodoActionPerformed
        // TODO add your handling code here:
        txtBuscar.setText(""); // Limpia la caja de texto del campo de búsqueda
         actualizarTablaVisual(controlador.obtenerTodosLosLibros(),tablaLibros); // Obtiene todos los libros registrados en el controlador y los actualiza la tabla para mostrarlos.
         jLabel2.setForeground(new java.awt.Color(0, 128, 0));
         jLabel2.setText("Mostrando todos los registros del sistema.");
    }//GEN-LAST:event_btnListarTodoActionPerformed

    private void btnInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercionActionPerformed
        // TODO add your handling code here:
        java.util.ArrayList<Libros> lista = controlador.obtenerTodosLosLibros(); // Obtiene la lista completa de libros almacenados en el controlador.
        controlador.ordenarPorInsercionManual(lista); // Ordena la lista de forma ascendente 
        actualizarTablaVisual(lista,tablaLibros);
        jLabel2.setForeground(new java.awt.Color(0, 128, 0));
        jLabel2.setText("Lista ordenada ascendentemente.");
    }//GEN-LAST:event_btnInsercionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        //Extraer el texto que el usuario digitó para buscar
        String criterio = txtBuscar.getText().trim();
        // Si el campo está vacío, asume que quiere ver todos los libros de nuevo
        if (criterio.isEmpty()) {
            jLabel2.setForeground(java.awt.Color.BLACK);
            jLabel2.setText("Campo vacío. Mostrando la lista completa de libros.");
            actualizarTablaVisual(controlador.obtenerTodosLosLibros(), tablaLibros);
            return;
    } 
        // Solicita al controlador que busque la lista principal extrayendo coincidencias del criterio
        java.util.ArrayList<Libros> librosFiltrados = controlador.buscarPorBiblioteca(criterio);
        // Valida si se encontraron libros o si la lista quedó vacía
        if (librosFiltrados.isEmpty()) {
            jLabel2.setForeground(java.awt.Color.RED);
            jLabel2.setText("No se encontraron libros asociados a la biblioteca: '" + criterio + "'.");

        // Limpia la tabla para que no se queden los datos de la búsqueda anterior
        actualizarTablaVisual(librosFiltrados, tablaLibros);
    } else { // Muestra en pantalla los elementos encontrados mediante la búsqueda.
            actualizarTablaVisual(librosFiltrados, tablaLibros);
            jLabel2.setForeground(new java.awt.Color(0, 128, 0)); 
            jLabel2.setText("Búsqueda finalizada. Se encontraron " + librosFiltrados.size() + " coincidencias.");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnInvertidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvertidasActionPerformed
        // TODO add your handling code here:
         java.util.ArrayList<String> unicas = controlador.obtenerBibliotecasUnicas(); // Obtiene una lista con los nombres únicos de las bibliotecas registradas
         javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaInvertidas.getModel(); // Obtiene el modelo de la tabla donde se mostrarán los resultados
         modelo.setRowCount(0); // Limpiar filas anteriores
         // Verifica si no existen bibliotecas registradas
         if (unicas.isEmpty()) {
             jLabel2.setForeground(java.awt.Color.RED);
             jLabel2.setText("No hay libros registrados para extraer bibliotecas.");
             return;         
    }    // Recorre cada nombre de biblioteca obtenido
         for (String b : unicas) {
             // Se ejecuta la inversión de texto puramente recursiva obligatoria
             String textoAlReves = controlador.invertirTextoRecursivo(b);
             modelo.addRow(new Object[]{b, textoAlReves});
    }
         jLabel2.setForeground(new java.awt.Color(0, 128, 0));
         jLabel2.setText("Nombres de bibliotecas invertidos de forma recursiva.");
    }//GEN-LAST:event_btnInvertidasActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void tablaLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibrosMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tablaLibros.getSelectedRow();  // Obtiene el índice de la fila seleccionada
        // Verifica que exista una fila seleccionada
        if (filaSeleccionada != -1) {
        // Obtener el ID numérico de la fila selecciona 
        int idLibro = Integer.parseInt(tablaLibros.getValueAt(filaSeleccionada, 0).toString());
        LibroEdicion = null;// Inicializa la referencia del libro a editar
         // Recorre la lista original del controlador para encontrar el objeto real
        for (Libros l : controlador.getListaLibros()) { 
            // Comprueba si el ID coincide con el libro seleccionado
            if (l.getId() == idLibro) {
                LibroEdicion = l;  // Guarda la referencia del objeto original para poder modificarlo
                break;
            }
        }
        // Verifica que el libro haya sido encontrad
        if (LibroEdicion != null) {
             // Carga los datos del libro en los campos del formulario
            txtTitulo.setText(LibroEdicion.getTitulo());
            txtAutor.setText(LibroEdicion.getAutor());
            txtFecha.setText(formatoFecha.format(LibroEdicion.getFechaPublicacion()));
            txtBiblioteca.setText(LibroEdicion.getBiblioteca());
            // Cambia el botón a Guardar Cambios
            btnRegistrar.setText("Guardar Cambios");
            // Cambia automáticamente a la pestaña del formulario de edición
            jTabbedPane1.setSelectedIndex(0);
            // Muestra un mensaje informando que el libro está listo para editarse
            jLabel2.setForeground(java.awt.Color.BLUE);
            jLabel2.setText("Editando el Libro ID: " + idLibro + ". Modifique los campos y guarde.");
        } else {
            // Muestra un mensaje de error si no se encontró el objeto original
            jLabel2.setForeground(java.awt.Color.RED);
            jLabel2.setText("Error: No se encontró el objeto original con el ID: " + idLibro);
        }
    }
    }//GEN-LAST:event_tablaLibrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             // Recorre todos los estilos visuales instalados en el sistema
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 // Verifica si el estilo actual se llama "Nimbus"
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());  // Establece Nimbus como apariencia de la aplicación
                    break; // Sale del ciclo una vez encontrado el estilo
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            // Registra el error en caso de que no sea posible aplicar el estilo Nimbus
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // Crea y muestra la ventana principal de la aplicación
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInsercion;
    private javax.swing.JButton btnInvertidas;
    private javax.swing.JButton btnListarTodo;
    private javax.swing.JButton btnMergeSort;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaInvertidas;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBiblioteca;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
